[build]
publish = 'dist'
command = 'yarn build'

[context.production.environment]
VUE_APP_API_ENDPOINT = 'https://q.trap.jp/api/v3'
VUE_APP_API_CLIENT_ID = 'lkEl3HAUIqFm5mUvxmWIanbWO7EBd9ttwBaW'

[context.dev.environment]
VUE_APP_API_ENDPOINT = 'https://traq-s-dev.tokyotech.org/api/v3'
VUE_APP_API_CLIENT_ID = '4yRM7RQvfLD71BbTwKfWzga2EgedPb22Vo6e'

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
