name: check yarn install & build
on:
  push:
    branches:
      - '**'

jobs:
  packages:
    name: check yarn install
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
      - name: check yarn install
        run: yarn install
  lint:
    name: run lint
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
      - name: check yarn install
        run: yarn install
      - name: run lint
        run: yarn lint --no-fix --max-warnings=0
  build:
    name: run build
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
      - name: check yarn install
        run: yarn install
      - name: run build
        run: yarn build
