name: check yarn install & build
on:
  push:
    branches:
      - '**'

jobs:
  packages:
    name: check yarn install
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn install
  lint:
    name: run lint
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn install
      - name: run lint
        run: yarn lint --no-fix --max-warnings=0
  build:
    name: run build
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn install
      - run: yarn build
