name: check yarn install & build
on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  packages:
    name: check yarn install
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.x
      - run: corepack enable
      - run: yarn install --immutable
  lint:
    name: run lint
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.x
      - run: corepack enable
      - run: yarn install --immutable
      - name: run lint
        run: yarn lint
  audit:
    name: audit dependencies
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.x
      - run: corepack enable
      - run: yarn install --immutable
      - name: audit dependencies
        run: yarn npm audit --all --recursive
  format:
    name: check format
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.x
      - run: corepack enable
      - run: yarn install --immutable
      - name: check format
        run: yarn format:check
  type-check:
    name: run type-check
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.x
      - run: corepack enable
      - run: yarn install --immutable
      - name: run type-check
        run: yarn type-check
  build:
    name: run build
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.x
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn build
